
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=sd
      - POSTGRES_PASSWORD=sdpass
      - POSTGRES_DB=sd
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./bdd/schema.sql:/docker-entrypoint-initdb.d/00-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sd -d sd"]
      interval: 5s
      timeout: 5s
      retries: 20

  adminer:
    image: adminer:4
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  ingestor:
    build:
      context: .
      dockerfile: ./docker/python.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: db          
      PGPORT: "5432"
      PGUSER: sd
      PGPASSWORD: sdpass
      PGDATABASE: sd
      STORAGE_JSONL: /data/storage.jsonl
      BATCH_SIZE: "200"
      SLEEP_SECS: "1.0"
      INGEST_FROM_START: "1"   
    volumes:
      - ./storage.jsonl:/data/storage.jsonl:ro
    command: ["python", "/app/services/ingestor/ingest_jsonl.py"]
  redis:
    image: redis:7-alpine
    command: >
      redis-server
      --appendonly yes
      --protected-mode no
      --maxmemory 2mb
      --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      PGHOST: db
      PGPORT: "5432"
      PGUSER: sd
      PGPASSWORD: sdpass
      PGDATABASE: sd
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      CACHE_TTL: "60"           
      OLLAMA_HOST: "http://172.17.0.1:11434"
      GEN_MODEL: "llama3.2:3b"
      EVAL_MODEL: "llama3.2:1b"
      NUM_THREAD: "2"
    ports:
      - "8000:8000"
  loadgen:
    build:
      context: .
      dockerfile: ./docker/python.Dockerfile
    depends_on:
      api:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      API_URL: "http://api:8000/query"
      PGHOST: "db"
      PGPORT: "5432"
      PGUSER: "sd"
      PGPASSWORD: "sdpass"
      PGDATABASE: "sd"
      DISTR: "poisson"        
      RATE: "2"              
      MU: "-2.0"              
      SIGMA: "1.0"
      DURATION: "120"         # segundos
      SLEEP: "1"
      SEED: "42"
    command: ["python", "/app/services/loadgen/main.py"]
    
volumes:
  pgdata:
